### ISSUE TITLE
Update electron

### ISSUE THREAD

**Issue by MikkelHegn** [Azure/service-fabric-explorer#18]
Currently depend on an electron version with know vulnerability:

The electron dependency defined in package-lock.json has a known critical severity security vulnerability in version range >= 1.7.0,< 1.7.11 and should be updated.

**Comment by stevshan** [comment]
Fixed in commit: [7973a6a91c031fc9700c55fddbed6ca87109db5e](https://github.com/Azure/service-fabric-explorer/commit/7973a6a91c031fc9700c55fddbed6ca87109db5e)
Released in [v18.1.2601](https://github.com/Azure/service-fabric-explorer/releases/tag/v18.1.2601)
