### ISSUE TITLE
Secondary build task fails: Require manual delete of gulp.js

### ISSUE THREAD

**Issue by sondreb** [Azure/service-fabric-explorer#21]
It appears that secondary builds using the "gulp Clean-Build", does not actually run build again. I have to manually delete the "gulp.js" output every time, to make it build the Sfx-Standalone project.

Node: v9.3.0
NPM: v5.5.1
TSC: v2.6.2

![image](https://user-images.githubusercontent.com/309938/35566752-cdf3bbd0-05c2-11e8-907d-f3d0f31cf571.png)

**Comment by sondreb** [comment]
A quick and dirty workaround is to delete the output from the gulp script at the end of Clean-Build task:

```js
gulp.task("Clean-Build",
    function (callback) {
        runSequence("Clean", "Build", "Clean-Script", callback);
    });

gulp.task("Clean-Script",
    function () {
        return del(["gulp.js"]);
    });
```

**Comment by stevshan** [comment]
Hey sondreb, thanks for the feedback. 

Clean-Build is supposed to build gulp.ts every time and overwrite gulp.js so that no need to remove gulp.js manually. There is a build task, Build:gulp-ts, which builds the gulp.ts. 

To help you troubleshoot, could you please share the gulpfile.js with us?

Thanks.

**Comment by sondreb** [comment]
Here is the generated gulp.js file: https://gist.github.com/sondreb/3b30ab3edb8132cb625db8c0bb88cc3a

**Comment by stevshan** [comment]
@sondreb hey, could you please share the **gulpfile.js**? gulpfile.js is the build script which builds gulp.js based on gulp.ts.

**Comment by sondreb** [comment]
The gulpfile.js is the same as in the repo :-)

This is the exact file I have: https://github.com/Azure/service-fabric-explorer/blob/master/src/Sfx-Standalone/gulpfile.js

**Comment by sondreb** [comment]
I can verify that running the gulp script from Visual Studio Code with the F5 debug runner works just fine, then it compiles the source every time. The issue is when I run it directly from console.

**Comment by stevshan** [comment]
@sondreb, it seems like a development related issue as it cannot be repro locally on my box. But could you please try the new branch "stevshan/modularization" as the TS compilation is changed?

Thanks.

**Comment by stevshan** [comment]
Close this issue for now. If the issue happens again, please feel free to reopen it. Thanks.
